- name: ansible.builtin.copy
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: copy .ssh/authorized_keys
      ansible.builtin.copy:
        src: authorized_keys
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
      become: yes
    - name: setting .ssh permissions
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700
        state: directory
      become: yes
    - name: setting authorized_keys permissions
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        mode: 0600
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: file
      become: yes
    - name: copy /etc/ssh/sshd_config
      ansible.builtin.copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
      become: yes
    - name: restart sshd
      service:
        name: sshd
        state: restarted
