- name: ansible.builtin.copy
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: copy .ssh/authorized_keys
      ansible.builtin.copy:
        src: authorized_keys
        dest: ~/.ssh/authorized_keys
      become: yes
    - name: setting authorized_keys permissions
      ansible.builtin.file:
        path: ~/.ssh/authorized_keys
        mode: 600
        state: file
      become: yes
    - name: /etc/ssh/sshd_config
      ansible.builtin.copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
      become: yes
    - name: restart sshd
      service:
        name: sshd
        state: restarted
    - name: restart sshd
      service:
        name: sshd
        state: restarted
