---
all:
  hosts:
  children:
    k8s01:
      hosts:
        ubuk8s01-ha01:
        ubuk8s01-ha02:
    ubuk8s01-w:
      hosts:
        ubuk8s01-w01:
        ubuk8s01-w02:
        ubuk8s01-w03:
    ubuk8s01-c:
      hosts:
        ubuk8s01-c01:
        ubuk8s01-c02:
        ubuk8s01-c03:
    Minecraft:
      hosts:
        ubuhamc-01:
        ubuhamc-02:
    Minecraft01:
      hosts:
        ubumc01-bungee01:
        ubumc01-spi01:
    Minecraft02:
      hosts:
        ubumc02-bungee01:
        ubumc02-spi01:
    ARK:
      hosts:
        k-ubuntu04:
    Management:
      hosts:
        ubu-mirrorcache:
        ubuprometheus01:
    Network:
      hosts:
        ubuwire01:
    Desktop_VM:
      hosts:
        LubuntuBiz:
    Others:
      hosts:
        ubudl:
        lubuntu01:
