---
all:
  hosts:
  children:
    Minecraft:
      hosts:
        ubuhamc-01:
        ubuhamc-02:
    Minecraft01:
      hosts:
        ubumc01-bungee01:
        ubumc01-spi01:
    Minecraft02:
      hosts:
        ubumc02-bungee01:
        ubumc02-spi01:
    ARK:
      hosts:
        k-ubuntu04:
    Management:
      hosts:
        ubu-mirrorcache:
    Network:
      hosts:
        ubuwire01:
    RHEL:
      hosts:
        rhel01:
    Others:
      hosts:
        ubudl:
