---
- name: install fail2ban
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
      become: yes
    - name: start fail2ban
      ansible.builtin.command:
        cmd: fail2ban-client start
      become: yes
      changed_when: no
