---
- name: install fail2ban
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
        state: present
      become: yes
      retries: 3
      delay: 5
    - name: install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
      become: yes
    - name: start fail2ban
      ansible.builtin.command:
        cmd: fail2ban-client start
      become: yes
      changed_when: no
    - name: enable fail2ban
      ansible.builtin.systemd_service:
        name: fail2ban.service
        enabled: yes
        state: started
      become: yes
