---
- name: update allnode
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
        state: present
      become: yes
      retries: 3
      delay: 5
      when: ansible_distribution in ['Ubuntu']
    - name: apt upgrade
      ansible.builtin.apt:
        upgrade: yes
        state: latest
      become: yes
      retries: 3
      delay: 5
      when: ansible_distribution in ['Ubuntu']
    - name: apt autoremove
      ansible.builtin.apt:
        autoremove: yes
      become: yes
      when: ansible_distribution in ['Ubuntu']
    - name: apt autoclean
      ansible.builtin.apt:
        autoclean: yes
      become: yes
      when: ansible_distribution in ['Ubuntu']

    - name: yum update
      ansible.builtin.yum:
        name: "*"
        state: latest
      become: yes
      when: ansible_os_family in ['RedHat']
